import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { type AddressInfo } from 'node:net';
import test from 'node:test';
import { parseMaterialPack } from '../shared/content.ts';
import { createApp, errorHandler } from '../server/app.ts';
import { LearningStore } from '../server/store.ts';

test('HTTP API validates requests, blocks cross-origin writes, and exercises a saved lesson', async t => {
  const pack = parseMaterialPack(JSON.parse(readFileSync(new URL('../content/polite-requests.json', import.meta.url), 'utf8')));
  const db = new DatabaseSync(':memory:');
  const app = createApp(new LearningStore(db, pack), ['http://127.0.0.1:5173']);
  app.use(errorHandler);
  const server = app.listen(0, '127.0.0.1');
  await new Promise<void>(resolve => server.once('listening', resolve));
  t.after(() => new Promise<void>(resolve => server.close(() => { db.close(); resolve(); })));
  const url = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const health = await fetch(`${url}/api/health`);
  assert.deepEqual(await health.json(), { status: 'ok', contentRevision: 1 });
  const bootstrap = await (await fetch(`${url}/api/bootstrap`)).json();
  assert.equal(bootstrap.pack.lessons.length, 3);
  const post = (route: string, body: unknown, origin = 'http://127.0.0.1:5173') => fetch(`${url}/api${route}`, { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: origin }, body: JSON.stringify(body) });
  assert.equal((await post('/profiles', { name: 'Extra', presentation: 'adult', explanationLanguage: 'en' }, 'https://untrusted.example')).status, 403);
  assert.equal((await post('/profiles', { name: '   ', presentation: 'adult', explanationLanguage: 'en' })).status, 400);
  const created = await post('/profiles', { name: 'Another learner', presentation: 'adult', explanationLanguage: 'zh' });
  assert.equal(created.status, 201);
  const profile = await created.json();
  const route = `/profiles/${profile.id}/lessons/${pack.lessons[0].id}`;
  assert.equal((await post(`${route}/advance`, {})).status, 200);
  assert.equal((await post(`${route}/answers`, { attemptId: 'invalid' })).status, 400);
  assert.equal((await fetch(`${url}/api/missing`)).status, 404);
  const before = await (await fetch(`${url}/api${route}`)).json();
  assert.equal(before.stage, 'practice');
  assert.equal(before.exerciseIndex, 0);
});


test('HTTP review requests use separate sessions and legacy lesson requests keep their default', async t => {
  const pack = parseMaterialPack(JSON.parse(readFileSync(new URL('../content/polite-requests.json', import.meta.url), 'utf8')));
  const db = new DatabaseSync(':memory:');
  let time = new Date('2026-10-03T00:00:00Z');
  const app = createApp(new LearningStore(db, pack, () => time));
  app.use(errorHandler);
  const server = app.listen(0, '127.0.0.1');
  await new Promise<void>(resolve => server.once('listening', resolve));
  t.after(() => new Promise<void>(resolve => server.close(() => { db.close(); resolve(); })));
  const url = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const route = `${url}/api/profiles/adult/lessons/${pack.lessons[0].id}`;
  const post = (operation: string, body: unknown) => fetch(`${route}/${operation}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  assert.equal((await fetch(`${route}?mode=invalid`)).status, 400);
  assert.equal((await post('advance', { mode: 'invalid' })).status, 400);
  assert.equal((await fetch(`${route}?mode=review`)).status, 409);
  assert.equal((await post('advance', {})).status, 200);
  const input = { attemptId: crypto.randomUUID(), exerciseId: pack.lessons[0].exercises[0].id, answer: 'milk', hinted: false, assisted: false };
  assert.equal((await post('answers', input)).status, 200);
  const lessonProgress = await (await post('advance', {})).json();
  assert.equal(lessonProgress.mode, 'lesson');
  assert.equal(lessonProgress.exerciseIndex, 1);
  time = new Date('2026-10-03T00:11:00Z');
  const review = await (await post('restart', { mode: 'review' })).json();
  assert.equal(review.mode, 'review');
  assert.deepEqual(await (await fetch(`${route}?mode=review`)).json(), review);
  const feedback = await post('answers', { ...input, attemptId: crypto.randomUUID(), answer: 'water', mode: 'review' });
  assert.equal(feedback.status, 200);
  assert.equal((await feedback.json()).mode, 'review');
  const finished = await (await post('advance', { mode: 'review' })).json();
  assert.equal(finished.stage, 'complete');
  assert.deepEqual(await (await fetch(route)).json(), lessonProgress);
});
